import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import "@/lib/fontawesome";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased lg:w-9/12 mx-auto`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        
        <Toaster
          position="top-center"
          richColors
          closeButton
          expand={false}
          toastOptions={{
            duration: 4000, 
            className: "rounded-xl shadow-md",
          }}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}